name: tournament_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  decimal: ^3.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  mailer: ^6.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
